version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ocx-sam-node"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-183688n200iqi"
s3_prefix = "ocx-sam-node"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
